USE [master]
GO

/****** Object:  Database [ClimaDB]    Script Date: 18/10/2022 1:28:29 a. m. ******/
CREATE DATABASE [ClimaDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ClimaDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ClimaDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ClimaDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ClimaDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ClimaDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ClimaDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ClimaDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ClimaDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ClimaDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ClimaDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ClimaDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ClimaDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ClimaDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ClimaDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ClimaDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ClimaDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ClimaDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ClimaDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ClimaDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ClimaDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ClimaDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ClimaDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ClimaDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ClimaDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ClimaDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ClimaDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ClimaDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ClimaDB] SET RECOVERY FULL 
GO

ALTER DATABASE [ClimaDB] SET  MULTI_USER 
GO

ALTER DATABASE [ClimaDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ClimaDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ClimaDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ClimaDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ClimaDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ClimaDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ClimaDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ClimaDB] SET  READ_WRITE 
GO


